### ISSUE TITLE
[1.0] Crash when clicking "Show All Recipes" for Extreme Crafting in JEI

### ISSUE THREAD

**Issue by SPMoo66** [KewaiiGamer/RiceCraftingTable#13]
When you click the top bar in JEI, Show All Recipes (http://i.imgur.com/7LyN2hr.png), the game crashes -

http://pastebin.com/uViS7JsC

I realize the crash report points to JEI, but this only happens with Extreme Crafting.

There doesn't seem to be a section for Extreme Crafting whatsoever when I'm scrolling through the all recipes section of JEI, so maybe it's related to that?

Other than this issue, the mod seems much better than it was before. Thanks! I really appreciate all the work that's gone into it lately!

**Comment by KewaiiGamer** [comment]
Thanks for reporting this issue. We are already aware of it and are trying to fix it. (Fast report :O)

**Comment by mezz** [comment]
Fixed in JEI 3.14.5
