### ISSUE TITLE
Recipes Do Not Use Ingredients 

### ISSUE THREAD

**Issue by ICY105** [KewaiiGamer/RiceCraftingTable#2]
Enough said, you can endlessly craft the item as it does not use the ingredients. Happens for every recipe I make. Tested with only rice crafting table and crafttweaker installed.

**Comment by KewaiiGamer** [comment]
Thank you so much for reporting this and many other issues. I'll be looking into them and try to fix.

**Comment by KewaiiGamer** [comment]
I already tried to reproduce this issue and when I use a Slime block to craft 4 sticks it consumes the slime block. Is it related to shapeless recipes only?

**Comment by ICY105** [comment]
This happens with either table, using both shaped and shapeless. However, it does not happen when auto-extracting items from the auto crafting table.

Try testing the mod when compiled versus in the development environment- I know from experience that they sometimes act differently.

**Comment by KewaiiGamer** [comment]
I am currently fixing my computer I just replaced windows with ubuntu but erased all my drive without making any backup. don't expect a new update in the next two weeks

**Comment by GazbonicAcid** [comment]
I hope to god you get your computer fixed SOON so you can fix this mod.
I really want to add this mod but I can't as long as it has this dupe bug.

**Comment by GazbonicAcid** [comment]
Welp...seems Rice Crafting Table was abandoned.
Your source is on Github so if it's an issue of not having backup of your code that's prevented you from working on it...
You're an idiot because you do have a backup, it's on Github.

**Comment by ghost** [comment]
Calling someone a an idiot is a sure fire way to get ignored. The author has stated that they are busy with real life events.

You're welcome to fix the bug yourself.

**Comment by jawsawn** [comment]
mods.rice.ExtremeCrafting.addShaped(projecte:item.pe_tome , [
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null], 
[null, null, null, null, null, null, null, null, null], 
[null, null, null, null, minecraft:barrier, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null]]);

does the same thing as this issue mentioned.

**Comment by KewaiiGamer** [comment]
It looks like this issue is being painful to fix. If anyone would like to contribute I would be grateful.

**Comment by ExpensiveKoala** [comment]
I put up a pull request with the rewrite. It fixes the issue.

**Comment by jawsawn** [comment]
@ExpensiveKoala do you have a comit for the jei too?

**Comment by ExpensiveKoala** [comment]
Not yet. I'm going to work on that next. ETA: 1 week.

**Comment by KewaiiGamer** [comment]
Wow Really? This is gonna improve this mod a lot. Thanks a lot for your help @ExpensiveKoala. I will be fixing the issue with the oreDictionary

**Comment by ExpensiveKoala** [comment]
While you're at it can you work on crafting recipes that give back an item? Specifically the issue #8.

**Comment by KewaiiGamer** [comment]
Yeah sure. I will have to look into how CraftTweaker compatibility works and prob start it from scratch
