### ISSUE TITLE
Crash When Shift+Clicking Recipes Out of Table

### ISSUE THREAD

**Issue by ICY105** [KewaiiGamer/RiceCraftingTable#3]
Shift clicking any recipe output from the table produces the following crash:
http://pastebin.com/jKvAv7ve

**Comment by KewaiiGamer** [comment]
Thank you so much for reporting this and many other issues. I'll be looking into them and try to fix.

**Comment by KewaiiGamer** [comment]
@ImCoolYeah105 I am not able to reproduce this bug. Can you send me the script that had the recipe you used
