### ISSUE TITLE
Ore Dictionary Item Are Not Used in the Recipe

### ISSUE THREAD

**Issue by ICY105** [KewaiiGamer/RiceCraftingTable#4]
If you make a recipe with ore dictionary items, then they are not "required" to complete the recipe. In other words, you can make the recipe with or without them.

**Comment by KewaiiGamer** [comment]
Thank you so much for reporting this and many other issues. I'll be looking into them and try to fix.

**Comment by KewaiiGamer** [comment]
if a recipe uses ONLY the oreDictionary version (for example: ore:cobblestone and ore:oreIron)then it bugs and lets me craft the recipe without even placing any items on the crafting grid.

If it uses an oreDictionary and any other item not that IS NOT the oreDict version (ore:oreIron and minecraft:cobblestone) then it works completely fine.

This works:
mods.rice.ExtremeCrafting.addShaped(<extrautils2:drum>,
[[<ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>, <extrautils2:compressedcobblestone>, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null]]);

This doesn't work
mods.rice.ExtremeCrafting.addShaped(<extrautils2:drum>,
[[<ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null],
[null, null, null, null, null, null, null, null, null]]);

**Comment by KewaiiGamer** [comment]
This issue has been fixed. A new version will be release soon!! :D
