### ISSUE TITLE
Texture size

### ISSUE THREAD

**Issue by ghost** [KewaiiGamer/RiceCraftingTable#5]
![textures_mipmap_0](https://cloud.githubusercontent.com/assets/16395640/20029015/0ea853f6-a30f-11e6-83b5-81e9aced6263.png)

Mezz recently released his "TextureDump" utility mod which dumps the texture map into a few files. Unfortunately, it looks like your mod is the worst offender by far out of all the mods in my pack. If you could shrink these down to a more reasonable size it would be much appreciated.

https://www.reddit.com/r/feedthebeast/comments/5b6bwg/exploring_the_texture_map/

**Comment by KewaiiGamer** [comment]
I just decreased the texture size back to 16x16. An update will be release shortly!
